version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    networks:
      - passin

  passin:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: passin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/postgres
      - API_BASE_URL=http://localhost:3333
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge
